variables:
  AUDIT_AWS_EC2_TAG_EXAMPLE_ALERT_RECIPIENT:
    description: email recipient for notification
    required: true
    type: string
    default:
  AUDIT_AWS_EC2_TAG_EXAMPLE_ALLOW_EMPTY:
    description: receive empty reports?
    required: true
    type: string
    default: false
  AUDIT_AWS_EC2_TAG_EXAMPLE_SEND_ON:
    description: always or change
    required: true
    type: string
    default: "change"
  AUDIT_AWS_EC2_TAG_EXAMPLE_EXPECTED_TAGS:
    description: the tag we want to see on instances
    required: true
    type: string
    default: '"EXAMPLE_TAG_1", "EXAMPLE_TAG_2"'
  AUDIT_AWS_EC2_TAG_EXAMPLE_TAG_LOGIC:
    description: '"or" or "and"'
    required: true
    type: string
    default: '"and"'
  AUDIT_AWS_EC2_TAG_EXAMPLE_REGIONS:
    description: list of AWS regions to check. Default is all regions
    required: true
    type: array
    default:
        - us-east-1
        - us-west-1
        - us-west-2


#       - ap-south-1
#       - ap-northeast-1
#       - ap-northeast-2
#       - ap-southeast-1
#       - ap-southeast-2
#       - eu-central-1
#       - eu-west-1
#       - sa-east-1

  AWS_LINUX_AMI:
    description: the ami id for latest AWS Linux
    switch: "PLAN::region"
    cases:
        us-east-1: ami-b73b63a0
        us-east-2: ami-58277d3d
        us-west-1: ami-23e8a343
        us-west-2: ami-5ec1673e
        ap-south-1: ami-34b4c05b
        ap-northeast-2: ami-983ce8f6
        ap-southeast-1: ami-b953f2da
        ap-southeast-2: ami-db704cb8
        ap-northeast-1: ami-0c11b26d
        eu-central-1: ami-f9619996
        eu-west-1: ami-9398d3e0
        sa-east-1: ami-97831ffb 
    type: case

# AMI's are for:
#   Amazon Linux AMI 2016.09.0 was released on 2016-09-27.

