variables:
  AUDIT_AWS_EC2_LINUX_CHECK_ALLOW_EMPTY:
    description: receive empty reports?
    required: true
    type: string
    default: false
  AUDIT_AWS_EC2_LINUX_CHECK_SEND_ON:
    description: always or change
    required: true
    type: string
    default: "change"
  AUDIT_AWS_EC2_LINUX_CHECK_RECIPIENT:
    description: "this is who the full json report goes to"
    required: true
    type: string
    default:
  AUDIT_AWS_EC2_LINUX_CHECK_REGIONS:
    description: list of AWS regions to check. Default is all regions
    required: true
    type: array
    default:
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
        - eu-west-1
  REGION:
    required: true
    default: PLAN::region
    type: string
  AWS_LINUX_AMI:
    description: the ami id for latest AWS Linux
    switch: "PLAN::region"
    cases:
        us-east-1: ami-b73b63a0
        us-east-2: ami-58277d3d
        us-west-1: ami-23e8a343
        us-west-2: ami-5ec1673e
        ap-south-1: ami-34b4c05b
        ap-northeast-2: ami-983ce8f6
        ap-southeast-1: ami-b953f2da
        ap-southeast-2: ami-db704cb8
        ap-northeast-1: ami-0c11b26d
        eu-central-1: ami-f9619996
        eu-west-1: ami-9398d3e0
        sa-east-1: ami-97831ffb 
    type: case
  AUDIT_AWS_EC2_LINUX_CHECK_OWNER_TAG:
      description: "Enter an AWS tag whose value is an email address of owner of the ELB object. (Optional)"
      required: false
      type: string
      default: "NOT_A_TAG"
